# excercise 3.8
places = ["Japan", "USA", "Italy", "Uk"]
print("List of places in original order ")
print(places)
print(f"\nSorted list {sorted(places)}")
print("\nChecking if list in original order")
print(places)
print(f"\nSorted list {sorted(places, reverse=True)}")
print("\nChecking if list in original order")
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
print(" ")
places.sort(reverse=True)
print(places)
